### ISSUE TITLE
Error resolving plugin

### ISSUE THREAD

**Issue by Avasam** [adamchainz/pre-commit-dprint#4]
I am unable to run dprint on the ci using pre-commit.ci, see: https://results.pre-commit.ci/run/github/590722908/1679682222.aZ0NgmLpSr-rivuEKQCgTg

```
Error resolving plugin https://plugins.dprint.dev/typescript-0.84.0.wasm: Error downloading https://plugins.dprint.dev/typescript-0.84.0.wasm - Error: https://plugins.dprint.dev/typescript-0.84.0.wasm: Dns Failed: resolve dns name 'plugins.dprint.dev:443': failed to lookup address information: Temporary failure in name resolution
```

**Comment by adamchainz** [comment]
Ah, this is because pre-commit.ci allows tools network access during the install phase, but not during the run phase. It seems dprint downloads plugins at run time. I think it would need some potentially heavy adaptation to work on pre-commit.ci.

I'm gonna close this and discuss archiving this repo in #3.
